name: CI - Dummy

on: 
  push: 
  workflow_dispatch:

jobs:
  ci:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
       uses: actions/checkout@v4

       - name: Say hello
       run: |
         echo "Hello from Github Action!"
         echo "Branch: ${{ github.ref_name }}"
         echo "SHA: ${{ github.sha }}
